[package]
name = "yamc_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
bevy = "0.16.1"
noise = { version = "0.8", features = ["images"] }
bevy_fly_camera = "*"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

#[profile.release]
#codegen-units = 1